services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:16-alpine
    container_name: ioffer-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ioffer_db}
      POSTGRES_USER: ${POSTGRES_USER:-ioffer_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ioffer_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ioffer_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ioffer_user} -d ${POSTGRES_DB:-ioffer_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB 数据库
  mongodb:
    image: mongo:7
    container_name: ioffer-mongodb
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  # 数据库管理界面 - Prisma Studio
  prisma-studio:
    build:
      context: ./backend
      dockerfile: Dockerfile.prisma-studio
    container_name: ioffer-prisma-studio
    ports:
      - "5556:5555"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ioffer_user}:${POSTGRES_PASSWORD:-ioffer_password}@postgres:5432/${POSTGRES_DB:-ioffer_db}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  # AI 服务 (Python FastAPI)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: ioffer-ai-service
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your_gemini_api_key}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-your_perplexity_api_key}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ioffer_user}:${POSTGRES_PASSWORD:-ioffer_password}@postgres:5432/${POSTGRES_DB:-ioffer_db}
      - SQL_DATABASE_URI=postgresql://${POSTGRES_USER:-ioffer_user}:${POSTGRES_PASSWORD:-ioffer_password}@postgres:5432/${POSTGRES_DB:-ioffer_db}
      - DATABASE_HOST=mongodb://mongodb:27017
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "${AI_SERVICE_PORT:-5555}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./ai-service:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 后端服务 (Node.js Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ioffer-backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-ioffer_user}:${POSTGRES_PASSWORD:-ioffer_password}@postgres:5432/${POSTGRES_DB:-ioffer_db}
      - JWT_SECRET=${JWT_SECRET:-MFiWT8JxJh/X81vPGkq4O2sY+okSd9hf9tBM/MQO0oo3f06cgdo+HrHpoXhTaudK4JAtsDFnRpQWvMz4DZ04Kw==}
      - PORT=${BACKEND_PORT:-8001}
      - NODE_ENV=${NODE_ENV:-development}
      - AI_SERVICE_URL=http://ai-service:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-your_gemini_api_key}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:-your_perplexity_api_key}
    ports:
      - "${BACKEND_PORT:-8001}:8001"
    depends_on:
      postgres:
        condition: service_healthy
      ai-service:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules

  # 前端服务 (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ioffer-frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8001}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-College Recommendation System}
      - NEXT_PUBLIC_APP_VERSION=${NEXT_PUBLIC_APP_VERSION:-1.0.0}
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${FRONTEND_PORT:-3005}:3000"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  ioffer_postgres_data:
    external: true
  mongodb_data:
    driver: local