version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ioffer-postgres
    environment:
      POSTGRES_DB: ioffer_db
      POSTGRES_USER: ioffer_user
      POSTGRES_PASSWORD: ioffer_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ioffer_user -d ioffer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local